#
# Makefile for the storage manager subsystem
#
# src/backend/storage/Makefile
#

subdir = src/backend/storage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = buffer DSMEngine file freespace GroundDB ipc large_object lmgr page smgr sync rpc kvstore rel_cache

include $(top_srcdir)/src/backend/common.mk
