#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/smgr
#
# IDENTIFICATION
#    src/backend/storage/smgr/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/smgr
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	tutorial_types.o \
	DataPageAccess.o \
	rpcserver.o \
	rpcclient.o \
	

include $(top_srcdir)/src/backend/common.mk
