#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/rpc
#
# IDENTIFICATION
#    src/backend/storage/rpc/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/rpc
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	DataPageAccess.o \
	rpcclient.o \
	rpcserver.o \
	tutorial_types.o
	

include $(top_srcdir)/src/backend/common.mk
