#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/DSMEngine
#
# IDENTIFICATION
#    src/backend/storage/DSMEngine/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/DSMEngine
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	cache.o \
	rdma_manager.o \
	ThreadPool.o

include $(top_srcdir)/src/backend/common.mk
